name: fetch
on:
  schedule:
    - cron: '*/30 * * * *' # Every 30 minutes
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write  # Allow write access to repository contents
jobs:
  fetch:
    name: Fetch
    if: github.repository_owner == 'aernjdz'
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v3

      - name: ⬡ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Pull latest changes
        run: git pull origin main || true  # Pull changes, ignore error if no changes
        
      - name: ⬇️ Install dependencies
        run: npm ci

      - name: ⚡️ Fetch data
        run: npm start

      - name: 📤 Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(fetch): Scheduled data fetch [skip ci]'
          file_pattern: 'outages/**'
          commit_options: '--no-verify'

      
